# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_xSHB2brHO-4ONw8cDQpVpdxdTXBsy_F
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

from sklearn.datasets import load_iris
import pandas as pd

iris_data = load_iris()
iris_df = pd.DataFrame(data=iris_data.data, columns=iris_data.feature_names)
display(iris_df.head())

plt.plot(PCA(n_components=4).fit_transform(iris_df)
)
plt.title("PCA graph ")
plt.axes="off"

correlation_matrix = iris_df.corr()
display(correlation_matrix)

covariance_matrix = iris_df.cov()
display(covariance_matrix)

import seaborn as sns

plt.figure(figsize=(8, 6))
sns.heatmap(covariance_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Covariance Matrix of Iris Dataset')
plt.show()

"""The correlation and covariance matrices show the relationships between the different features of the Iris dataset:

*   **Correlation Matrix:** This matrix shows the linear relationship between pairs of features, scaled between -1 and 1. A value close to 1 indicates a strong positive correlation (as one feature increases, the other tends to increase), a value close to -1 indicates a strong negative correlation (as one feature increases, the other tends to decrease), and a value close to 0 indicates a weak or no linear correlation. In the Iris dataset correlation matrix, we can see strong positive correlations between 'petal length (cm)' and 'petal width (cm)', and also between 'sepal length (cm)' and 'petal length (cm)', and 'sepal length (cm)' and 'petal width (cm)'. This suggests that these measurements tend to increase together.

*   **Covariance Matrix:** This matrix shows the directional relationship between pairs of features, but it is not scaled. The diagonal elements represent the variance of each feature, while the off-diagonal elements represent the covariance between pairs of features. A positive covariance indicates that the features tend to increase or decrease together, while a negative covariance indicates that one tends to increase when the other decreases. The magnitude of the covariance is not easily interpretable on its own, but it is used in calculations like PCA. The heatmap visualization helps to see the relative strength of the covariance between features. From the heatmap, we can visually confirm the strong positive relationships seen in the correlation matrix, particularly between the petal measurements.
"""